export const LINUX_INSTALL_SH = [
  "#!/bin/sh",
  "# AI Console Agent installer for Linux/macOS (Go binary)",
  "# Usage:",
  "#   TOKEN=... SERVER=https://console sh -c \"$(curl -fsSL https://console/agent/install.sh)\"",
  "#   ./install.sh --token=... --server=https://console [--binary-url=...]",
  "set -eu",
  "",
  'TOKEN="${TOKEN:-}"',
  'SERVER="${SERVER:-}"',
  'BINARY_URL="${BINARY_URL:-}"',
  'USE_PATH="${USE_PATH:-}"',
  "",
  'for arg in "$@"; do',
  "  case $arg in",
  '    --token=*) TOKEN="${arg#--token=}" ;;',
  '    --server=*) SERVER="${arg#--server=}" ;;',
  '    --binary-url=*) BINARY_URL="${arg#--binary-url=}" ;;',
  '    --use-path) USE_PATH="1" ;;',
  "  esac",
  "done",
  "",
  'if [ -z "$TOKEN" ] || [ -z "$SERVER" ]; then',
  '  echo "Error: TOKEN/SERVER env or --token and --server are required"',
  '  echo "Usage: TOKEN=... SERVER=https://console sh -c \\"\\$(curl -fsSL https://console/agent/install.sh)\\""',
  "  exit 1",
  "fi",
  "",
  'DIR="$HOME/.ai-console-agent"',
  'mkdir -p "$DIR"',
  'BINDIR="$DIR/bin"',
  'mkdir -p "$BINDIR"',
  'BINARY="$BINDIR/ai-agent"',
  "",
  "OS=$(uname -s | tr '[:upper:]' '[:lower:]')",
  "ARCH=$(uname -m)",
  'case "$ARCH" in',
  '  x86_64|amd64) ARCH="amd64" ;;',
  '  aarch64|arm64) ARCH="arm64" ;;',
  "  *)",
  '    echo "Error: unsupported architecture: $ARCH"',
  "    exit 1",
  "    ;;",
  "esac",
  "",
  'if [ -n "$BINARY_URL" ]; then',
  '  echo "Downloading agent binary from $BINARY_URL ..."',
  '  curl -fsSL -o "$BINARY" "$BINARY_URL"',
  'elif [ "$USE_PATH" = "1" ] && command -v ai-agent >/dev/null 2>&1; then',
  '  echo "Using existing ai-agent from PATH"',
  '  cp "$(command -v ai-agent)" "$BINARY"',
  "else",
  '  BINARY_URL="${SERVER}/agent/binary/${OS}/${ARCH}"',
  '  echo "Downloading agent binary from $BINARY_URL ..."',
  '  curl -fsSL -o "$BINARY" "$BINARY_URL"',
  "fi",
  "",
  'chmod +x "$BINARY"',
  "",
  'echo "Enrolling agent..."',
  '"$BINARY" --enroll-only --token="$TOKEN" --server="$SERVER"',
  "",
  'if [ "$OS" = "linux" ] && command -v systemctl >/dev/null 2>&1; then',
  '  UNIT_FILE="$HOME/.config/systemd/user/ai-console-agent.service"',
  '  mkdir -p "$(dirname "$UNIT_FILE")"',
  "  cat > \"$UNIT_FILE\" <<EOF",
  "[Unit]",
  "Description=AI Console Agent",
  "After=network.target",
  "",
  "[Service]",
  "ExecStart=$BINARY",
  "Restart=always",
  "RestartSec=10",
  "Environment=HOME=$HOME",
  "Environment=PATH=$PATH",
  "",
  "[Install]",
  "WantedBy=default.target",
  "EOF",
  "  systemctl --user daemon-reload",
  "  systemctl --user enable ai-console-agent",
  "  systemctl --user start ai-console-agent",
  "  loginctl enable-linger \"$USER\" 2>/dev/null || true",
  '  echo "Installed as systemd user service (linger enabled). Check: systemctl --user status ai-console-agent"',
  "",
  'elif [ "$OS" = "darwin" ] && command -v launchctl >/dev/null 2>&1; then',
  '  PLIST="$HOME/Library/LaunchAgents/com.ai-console.agent.plist"',
  "  cat > \"$PLIST\" <<EOF",
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
  "<plist version=\"1.0\">",
  "<dict>",
  "  <key>Label</key><string>com.ai-console.agent</string>",
  "  <key>ProgramArguments</key>",
  "  <array>",
  "    <string>$BINARY</string>",
  "  </array>",
  "  <key>RunAtLoad</key><true/>",
  "  <key>KeepAlive</key><true/>",
  "  <key>EnvironmentVariables</key>",
  "  <dict><key>HOME</key><string>$HOME</string></dict>",
  "</dict>",
  "</plist>",
  "EOF",
  '  launchctl unload "$PLIST" 2>/dev/null || true',
  '  launchctl load "$PLIST"',
  '  echo "Installed as launchd service. Check: launchctl list | grep ai-console"',
  "else",
  '  echo "No service manager detected. Run manually: $BINARY"',
  "fi",
  "",
  'for rcfile in "$HOME/.bashrc" "$HOME/.zshrc"; do',
  '  if [ -f "$rcfile" ] && ! grep -q ".ai-console-agent/creds" "$rcfile" 2>/dev/null; then',
  "    cat >> \"$rcfile\" <<'RCEOF'",
  "",
  "# AI Console: auto-load credentials for CLI tools",
  'for f in "$HOME"/.ai-console-agent/creds/*.sh; do',
  '  [ -f "$f" ] && . "$f"',
  "done",
  "RCEOF",
  '    echo "  added credential loading to $(basename \"$rcfile\")"',
  "  fi",
  "done",
  "",
  'echo "Done. Agent installed to $BINARY"',
  "",
].join("\n")
