// AI Console Agent install script, served verbatim by GET /agent/install.sh.
//
// Keep this LOGICALLY IN SYNC with agent/install.sh (the canonical, fully
// commented version). We inline the script here instead of reading
// agent/install.sh at request time because the Docker runtime stage copies
// console/agent-dist (binaries + manifest) but NOT the agent/ source tree —
// so that file is absent in production. Both versions share the same core
// guarantees:
//   1. The downloaded binary's SHA-256 is verified against
//      /agent/manifest.json; a custom --binary-url requires --binary-sha256.
//   2. The download goes to $BINARY.tmp and is atomically mv'd into place, so
//      a failed/interrupted download can never leave a half-written binary
//      at the target path that blocks all subsequent re-installs (this is
//      exactly the curl:(23) failure mode seen on WSL when a stale partial
//      binary from a prior run could not be overwritten).
// NOTE: unlike agent/install.sh, this served version does NOT enforce HTTPS —
// HTTP is allowed so the same one-liner works for localhost dev without extra
// flags. agent/install.sh (the canonical copy) still enforces HTTPS.
export const LINUX_INSTALL_SH = [
  "#!/bin/sh",
  "# AI Console Agent installer for Linux/macOS (Go binary).",
  "# Usage:",
  '#   TOKEN=... SERVER=https://console sh -c "$(curl -fsSL https://console/agent/install.sh)"',
  "#   ./install.sh --token=... --server=https://console [--binary-url=... --binary-sha256=...]",
  "# Verifies the binary against /agent/manifest.json (SHA-256).",
  "set -eu",
  "",
  'TOKEN="${TOKEN:-}"',
  'SERVER="${SERVER:-}"',
  'BINARY_URL="${BINARY_URL:-}"',
  'BINARY_SHA256="${BINARY_SHA256:-}"',
  "",
  'for arg in "$@"; do',
  "  case $arg in",
  '    --token=*) TOKEN="${arg#--token=}" ;;',
  '    --server=*) SERVER="${arg#--server=}" ;;',
  '    --binary-url=*) BINARY_URL="${arg#--binary-url=}" ;;',
  '    --binary-sha256=*) BINARY_SHA256="${arg#--binary-sha256=}" ;;',
  "  esac",
  "done",
  "",
  'if [ -z "$TOKEN" ] || [ -z "$SERVER" ]; then',
  '  echo "Error: TOKEN/SERVER env or --token and --server are required" >&2',
  '  echo "Usage: TOKEN=... SERVER=https://console sh -c \\"\\$(curl -fsSL https://console/agent/install.sh)\\"" >&2',
  "  exit 1",
  "fi",
  "",
  "# Pick a SHA-256 tool once; refuse to install without integrity verification.",
  "if command -v sha256sum >/dev/null 2>&1; then",
  '  SHA256_CMD="sha256sum"',
  "elif command -v shasum >/dev/null 2>&1; then",
  '  SHA256_CMD="shasum -a 256"',
  "else",
  "  echo \"Error: neither sha256sum nor 'shasum -a 256' is available. Install one before continuing.\" >&2",
  "  exit 1",
  "fi",
  "",
  "# A custom BINARY_URL must be paired with BINARY_SHA256.",
  'if [ -n "$BINARY_URL" ] && [ -z "$BINARY_SHA256" ]; then',
  '  echo "Error: BINARY_URL requires BINARY_SHA256 (integrity verification)." >&2',
  "  exit 1",
  "fi",
  "",
  'DIR="$HOME/.ai-console-agent"',
  'mkdir -p "$DIR"',
  'chmod 700 "$DIR"',
  'BINDIR="$DIR/bin"',
  'mkdir -p "$BINDIR"',
  'chmod 700 "$BINDIR"',
  'BINARY="$BINDIR/ai-agent"',
  "",
  "OS=$(uname -s | tr '[:upper:]' '[:lower:]')",
  "ARCH=$(uname -m)",
  'case "$ARCH" in',
  '  x86_64|amd64) ARCH="amd64" ;;',
  '  aarch64|arm64) ARCH="arm64" ;;',
  "  *)",
  '    echo "Error: unsupported architecture: $ARCH" >&2',
  "    exit 1",
  "    ;;",
  "esac",
  "",
  "verify_sha256() {",
  "  # $1 = file, $2 = expected hex",
  "  local got",
  "  got=$($SHA256_CMD \"$1\" | awk '{print $1}')",
  '  if [ "$got" != "$2" ]; then',
  '    echo "Error: sha256 mismatch for $1: got $got, expected $2" >&2',
  "    return 1",
  "  fi",
  "}",
  "",
  'if [ -n "$BINARY_URL" ]; then',
  '  echo "Downloading agent binary from $BINARY_URL ..."',
  '  curl -fsSL -o "$BINARY" "$BINARY_URL"',
  '  verify_sha256 "$BINARY" "$BINARY_SHA256" || { rm -f "$BINARY"; exit 1; }',
  "fi",
  "",
  'if [ ! -f "$BINARY" ]; then',
  '  MANIFEST_URL="${SERVER%/}/agent/manifest.json"',
  '  BINARY_URL="${SERVER%/}/agent/binary/${OS}/${ARCH}"',
  '  echo "Fetching manifest from $MANIFEST_URL ..."',
  '  MANIFEST_TMP="$(mktemp)"',
  "  trap 'rm -f \"$MANIFEST_TMP\" \"$BINARY.tmp\"' EXIT",
  '  curl -fsSL -o "$MANIFEST_TMP" "$MANIFEST_URL"',
  '  EXPECTED_SHA=$(sed -n "s/.*\\"${OS}-${ARCH}\\":[[:space:]]*{[^}]*\\"sha256\\":[[:space:]]*\\"\\([0-9a-f]\\+\\)\\".*/\\1/p" "$MANIFEST_TMP" | head -n1)',
  '  if [ -z "$EXPECTED_SHA" ]; then',
  "    EXPECTED_SHA=$(python3 -c \"import json,sys; m=json.load(open('$MANIFEST_TMP')); print(m['binaries']['${OS}-${ARCH}']['sha256'])\" 2>/dev/null || true)",
  "  fi",
  '  if [ -z "$EXPECTED_SHA" ]; then',
  '    echo "Error: manifest has no sha256 for ${OS}-${ARCH}" >&2',
  "    exit 1",
  "  fi",
  '  echo "Downloading agent binary from $BINARY_URL ..."',
  '  curl -fsSL -o "$BINARY.tmp" "$BINARY_URL"',
  '  verify_sha256 "$BINARY.tmp" "$EXPECTED_SHA" || { rm -f "$BINARY.tmp"; exit 1; }',
  '  mv "$BINARY.tmp" "$BINARY"',
  "fi",
  "",
  'chmod 700 "$BINARY"',
  "",
  'echo "Enrolling agent..."',
  '"$BINARY" --enroll-only --token="$TOKEN" --server="$SERVER"',
  "",
  'if [ "$OS" = "linux" ] && command -v systemctl >/dev/null 2>&1; then',
  '  UNIT_FILE="$HOME/.config/systemd/user/ai-console-agent.service"',
  '  mkdir -p "$(dirname "$UNIT_FILE")"',
  "  cat > \"$UNIT_FILE\" <<EOF",
  "[Unit]",
  "Description=AI Console Agent",
  "After=network.target",
  "",
  "[Service]",
  "ExecStart=$BINARY",
  "Restart=always",
  "RestartSec=10",
  "Environment=HOME=$HOME",
  "Environment=PATH=$PATH",
  "",
  "[Install]",
  "WantedBy=default.target",
  "EOF",
  "  systemctl --user daemon-reload",
  "  systemctl --user enable ai-console-agent",
  "  systemctl --user start ai-console-agent",
  "  loginctl enable-linger \"$USER\" 2>/dev/null || true",
  '  echo "Installed as systemd user service (linger enabled). Check: systemctl --user status ai-console-agent"',
  "",
  'elif [ "$OS" = "darwin" ] && command -v launchctl >/dev/null 2>&1; then',
  '  PLIST="$HOME/Library/LaunchAgents/com.ai-console.agent.plist"',
  "  cat > \"$PLIST\" <<EOF",
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
  "<plist version=\"1.0\">",
  "<dict>",
  "  <key>Label</key><string>com.ai-console.agent</string>",
  "  <key>ProgramArguments</key>",
  "  <array>",
  "    <string>$BINARY</string>",
  "  </array>",
  "  <key>RunAtLoad</key><true/>",
  "  <key>KeepAlive</key><true/>",
  "  <key>EnvironmentVariables</key>",
  "  <dict><key>HOME</key><string>$HOME</string></dict>",
  "</dict>",
  "</plist>",
  "EOF",
  '  launchctl unload "$PLIST" 2>/dev/null || true',
  '  launchctl load "$PLIST"',
  '  echo "Installed as launchd service. Check: launchctl list | grep ai-console"',
  "else",
  '  echo "No service manager detected. Run manually: $BINARY"',
  "fi",
  "",
  'for rcfile in "$HOME/.bashrc" "$HOME/.zshrc"; do',
  '  if [ -f "$rcfile" ] && ! grep -q ".ai-console-agent/creds" "$rcfile" 2>/dev/null; then',
  "    cat >> \"$rcfile\" <<'RCEOF'",
  "",
  "# AI Console: auto-load credentials for CLI tools",
  'for f in "$HOME"/.ai-console-agent/creds/*.sh; do',
  '  [ -f "$f" ] && . "$f"',
  "done",
  "RCEOF",
  '    echo "  added credential loading to $(basename "$rcfile")"',
  "  fi",
  "done",
  "",
  'echo "Done. Agent installed to $BINARY"',
  "",
].join("\n")
